### gridworld 4*4


    This is a WindyGrid World environment.
    You are an agent on an MxN grid and your goal is to reach the terminal
    state at the top left or the bottom right corner.
    

    For example, a 4x4 grid looks as follows:

    T  o  o  o
    o  x  o  o
    o  o  o  o
    o  o  o  T

    x is your position and T are the two terminal states.

    You can take actions in each direction (UP=0, RIGHT=1, DOWN=2, LEFT=3).
    Actions going off the edge leave you in your current state.
    You receive a reward of -1 at each step until you reach a terminal state.
    Notice : the wind is blowing , so you won't always move in the direction you intend.
    """"""You dont need to use the AMAlearn package on this hands on session"""""
    

### Getting Started

Run the following code and observe the result.

In [4]:
import random
import pprint

In [22]:
%run WindyGridworld.ipynb

env =  WindyGridworldEnv()
env.reset()

for _ in range(10):
    env._render()
    state, reward, done, info = env.step(env.action_space.sample()) # Take a random action
    print(info)
env.close()

T  o  x  o
o  o  o  o
o  o  o  o
o  o  o  T
{'prob': 1.0}
T  o  o  x
o  o  o  o
o  o  o  o
o  o  o  T
{'prob': 1.0}
T  o  o  x
o  o  o  o
o  o  o  o
o  o  o  T
{'prob': 0.8}
T  o  x  o
o  o  o  o
o  o  o  o
o  o  o  T
{'prob': 0.8}
T  o  x  o
o  o  o  o
o  o  o  o
o  o  o  T
{'prob': 0.8}
T  x  o  o
o  o  o  o
o  o  o  o
o  o  o  T
{'prob': 0.8}
T  o  o  o
o  x  o  o
o  o  o  o
o  o  o  T
{'prob': 0.8}
T  x  o  o
o  o  o  o
o  o  o  o
o  o  o  T
{'prob': 0.8}
T  x  o  o
o  o  o  o
o  o  o  o
o  o  o  T
{'prob': 0.8}
T  x  o  o
o  o  o  o
o  o  o  o
o  o  o  T
{'prob': 0.2}


What are the action space and the state space?

In [ ]:
print(env.action_space)
print(env.observation_space)


action space is showin which actios we can take i an itteration, and state space shows howmany and which states we can get in with possible action that we can take.

In [7]:
print(env.nA)
print(env.nS)

4
16


What does the following code indicate?

In [8]:
print(env.P[7][2])

[(0.8, 11, -1.0, False), (0.2, 7, -1.0, False)]


env.P represents the transition probabilities of the environment. env.P[7] is the transition probabilities of 8th state of our enviroment. env.P[7][2] is when we choose to go down.It contains information about the probability, next state, reward and whether or not our action is done. because of windy environment done-action may be different from our -takenaction.



reward is 0.0 if we are stuck in the terminal state, else we will get a -1.0 reward. also, done turns true when we are on the last state, terminal state.

Find the best policy using the Value Iteration algorithm.

In [31]:
def value_iteration(env, theta=0.0001, discount_factor=1.0):
    """
    Value Iteration Algorithm.
    
    Args:
        env: OpenAI env. env.P represents the transition probabilities of the environment.
            env.P[s][a] is a list of transition tuples (prob, next_state, reward, done).
            env.nS is a number of states in the environment. 
            env.nA is a number of actions in the environment.
        theta: We stop evaluation once our value function change is less than theta for all states.
        discount_factor: Gamma discount factor.
        
    Returns:
        A tuple (policy, V) of the optimal policy and the optimal value function.        
    """
    

    V = np.zeros(env.nS)
    policy = np.zeros([env.nS, env.nA])
    itter = 0
    while 1:
        itter += 1
        delta = 0
        for state in range(env.nS):
            v = V[state]
            states_value = np.zeros(env.nA)
            for action in range(env.nA):
                temp_t = env.P[state][action]
                p_s_sp, sp, r, d = temp_t[0]
                temp_sum = (p_s_sp * ( r + discount_factor * V[sp] ))
                if len(temp_t) == 2:
                    p_s_sp, sp, r, d = temp_t[1]
                    states_value[action] = p_s_sp * ( r + discount_factor * V[sp] )  + temp_sum
                else:
                    states_value[action] = temp_sum
            V[state] = np.max(states_value)
            delta = max( delta, abs( v - V[state] ) )
            
        if delta < theta or itter == 10 :
            
            for state in range(env.nS):
                temp_best_action = 0 
                for action in range(env.nA):
                    temp_t = env.P[state][action]
                    p_s_sp, sp, r, d = temp_t[0]
                    temp_sum = (p_s_sp * ( r + discount_factor * V[sp] ))
                    if len(temp_t) == 2:
                        p_s_sp, sp, r, d = temp_t[1]
                        V_temp = p_s_sp * ( r + discount_factor * V[sp] )  + temp_sum
                    else:
                        V_temp = temp_sum
                    if action == 0:
                        temp_v = V_temp
                    bigger_V = [temp_v, V_temp]
                    bigger_value = max(bigger_V)
                    bigger_index = bigger_V.index(bigger_value)
                   # print(V_temp)
                    temp_v = bigger_value
                    if bigger_index == 1 :
                        temp_best_action = action
                policy[state][temp_best_action] = 1
            break
    # Implement!
    return policy, V

Print what the best action in each state is.

In [32]:
policy, V = value_iteration(env)
print(policy)

[[1. 0. 0. 0.]
 [0. 0. 0. 1.]
 [0. 0. 0. 1.]
 [0. 0. 1. 0.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 1. 0.]
 [1. 0. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 1. 0.]
 [0. 0. 1. 0.]
 [0. 1. 0. 0.]
 [0. 1. 0. 0.]
 [0. 1. 0. 0.]
 [1. 0. 0. 0.]]


Print value in each state is.

In [33]:
for i in range(V.shape [0]):
    print('state[' + "{:2d}".format(i) + '] value is :' + str(V[i]) + '\n')

state[ 0] value is :0.0

state[ 1] value is :-1.249999872

state[ 2] value is :-2.4999979008000004

state[ 3] value is :-3.7498972160000004

state[ 4] value is :-1.5255955456

state[ 5] value is :-2.6279950336000004

state[ 6] value is :-3.1399946240000003

state[ 7] value is :-2.499994624

state[ 8] value is :-2.82247630848

state[ 9] value is :-3.0099998720000003

state[10] value is :-2.0499998720000003

state[11] value is :-1.249999872

state[12] value is :-3.0

state[13] value is :-2.0

state[14] value is :-1.0

state[15] value is :0.0



Find the best policy using the Policy Iteration algorithm.

In [16]:
def policy_eval(policy, env, discount_factor=1.0, theta=0.00001):
    """
    Evaluate a policy given an environment and a full description of the environment's dynamics.
    
    Args:
        policy: [S, A] shaped matrix representing the policy.
        env: OpenAI env. env.P represents the transition probabilities of the environment.
            env.P[s][a] is a list of transition tuples (prob, next_state, reward, done).
            env.nS is a number of states in the environment. 
            env.nA is a number of actions in the environment.
        theta: We stop evaluation once our value function change is less than theta for all states.
        discount_factor: Gamma discount factor.
    
    Returns:
        Vector of length env.nS representing the value function.
    """
    # Start with a random (all 0) value function
    V = np.zeros(env.nS)
    itter = 0
    while 1:
        itter += 1
        delta = 0
        for state in range(env.nS):
            v = V[state]
            temp_v = np.zeros(4)
            for action in range(env.nA):
                temp_t = env.P[state][action]
                #print(temp_t)
                p_s_sp, sp, r, d = temp_t[0]
                temp_sum = (p_s_sp * ( r + discount_factor * V[sp] ))
                if len(temp_t) == 2:
                    p_s_sp, sp, r, d = temp_t[1]
                    temp_v[action] = p_s_sp * ( r + discount_factor * V[sp] )  + temp_sum
                else:
                    temp_v[action] = temp_sum
            ts = 0
            for action in range(4):
                ts += policy[state][action]*temp_v[action]/itter
            V[state] = v*(itter-1)/itter + ts
            delta = max( delta, abs( v - V[state] ) )
            
        if delta < theta :
            break
    return np.array(V)

In [27]:
V=policy_eval(policy, env)
for i in range(V.shape [0]):
    print('state[' + "{:2d}".format(i) + '] value is :' + str(V[i]) + '\n')


state[ 0] value is :0.0

state[ 1] value is :-1.2492731736636988

state[ 2] value is :-2.493903475618819

state[ 3] value is :-3.7233223035698617

state[ 4] value is :-1.5499196707232803

state[ 5] value is :-2.7803460022637165

state[ 6] value is :-3.1276749941709414

state[ 7] value is :-2.4911640155094306

state[ 8] value is :-2.8261628579871396

state[ 9] value is :-3.0035542047627515

state[10] value is :-2.0487877367705023

state[11] value is :-1.2492731736636988

state[12] value is :-2.993941608042092

state[13] value is :-1.9993932038834965

state[14] value is :-1.0

state[15] value is :0.0



policy_improvement

In [79]:
def policy_eval_1(V,policy, env, discount_factor=1.0, theta=0.00001):
    """
    Evaluate a policy given an environment and a full description of the environment's dynamics.
    
    Args:
        policy: [S, A] shaped matrix representing the policy.
        env: OpenAI env. env.P represents the transition probabilities of the environment.
            env.P[s][a] is a list of transition tuples (prob, next_state, reward, done).
            env.nS is a number of states in the environment. 
            env.nA is a number of actions in the environment.
        theta: We stop evaluation once our value function change is less than theta for all states.
        discount_factor: Gamma discount factor.
    
    Returns:
        Vector of length env.nS representing the value function.
    """
    # Start with a random (all 0) value function
    while True:
            delta = 0
            for state in range(env.nS):
                v = 0
                v_temp = V[state]
                states_value = 0
                for action, action_probability in enumerate(policy[state]):
                    for p_s_ns, next_state, state_reward, done in env.P[state][action]:
                        states_value += action_probability * p_s_ns * (state_reward + discount_factor * V[next_state])
                v = states_value
                delta = max(delta, np.abs(v_temp - v))
                V[state] = v
            if delta < theta:
                    break
    return V

In [92]:

best_actions = []

def policy_improvement(env, policy_eval_fn=policy_eval_1, discount_factor=1.0):
    policy = np.ones([env.nS, env.nA]) / env.nA
    states_value = np.zeros(env.nS)
    while True:
            states_values = policy_eval_1(states_value ,policy, env)
            policy_stable = True
            for state in range(env.nS):
                action_values = np.zeros(env.nA)
                chosen_action = np.argmax(policy[state])
                for action in range(env.nA):
                    for p_s_ns, next_state, state_reward, done in env.P[state][action]:
                        action_values[action] += p_s_ns * (state_reward + discount_factor * states_value[next_state])
                best_action = np.argmax(action_values)
                if  chosen_action != best_action:
                    policy_stable = False
                policy[state] = np.eye(env.nA)[best_action]
                best_actions.append(best_action)
            if policy_stable :
                return policy ,states_value 
    #return policy, np.zeros(env.nS)

Print what the best action in each state is.

In [93]:
policy, V = policy_improvement(env)
for i in range(len(best_actions)):
    print('For state number ' +str(i) + " "+"{:2d}".format(best_actions[i]) +  '\n')

For state number 0  0

For state number 1  3

For state number 2  3

For state number 3  2

For state number 4  0

For state number 5  3

For state number 6  2

For state number 7  2

For state number 8  0

For state number 9  2

For state number 10  2

For state number 11  2

For state number 12  1

For state number 13  1

For state number 14  1

For state number 15  0

For state number 16  0

For state number 17  3

For state number 18  3

For state number 19  3

For state number 20  0

For state number 21  0

For state number 22  2

For state number 23  2

For state number 24  0

For state number 25  2

For state number 26  2

For state number 27  2

For state number 28  1

For state number 29  1

For state number 30  1

For state number 31  0

For state number 32  0

For state number 33  3

For state number 34  3

For state number 35  3

For state number 36  0

For state number 37  0

For state number 38  2

For state number 39  2

For state number 40  0

For state number 41  2

Fo

Print value in each state is.

In [86]:
V

array([ 0.        , -1.25      , -2.5       , -3.75000001, -1.5256    ,
       -2.628     , -3.14      , -2.5       , -2.82248   , -3.01      ,
       -2.05      , -1.25      , -3.        , -2.        , -1.        ,
        0.        ])